export const techIcons = [
  {
    src: "/Typescript_logo_2020.svg.png",
    alt: "TS",
  },
  {
    src: "/Python-logo-notext.svg.png",
    alt: "Python",
  },
  { src: "/c_language_img.png", alt: "C" },
  {
    src: "/java-programming-language-icon.png",
    alt: "Java",
  },
  {
    src: "/node-js-icon-454x512-nztofx17.png",
    alt: "Node.js",
  },
  { src: "/React-icon.svg.png", alt: "React" },
  { src: "/tailwindcss.png", alt: "Tailwind" },
  { src: "/mongodb.png", alt: "MongoDB" },
  {
    src: "/aws-logo-920x920-sue-v03.png",
    alt: "AWS",
  },
  { src: "/stripe.png", alt: "Stripe" },
  { src: "/Git_icon.svg.png", alt: "Git" },
  { src: "/astro.png", alt: "Astro" },
  { src: "/Amazon-S3-Logo.png", alt: "S3" },
  {
    src: "/aws-ec2-icon-1696x2048-nhw31ife.png",
    alt: "EC2",
  },
  { src: "/unity-loog.png", alt: "Unity" },
  { src: "/express2.png", alt: "Express" },
];

export const slugs = [
  "typescript",
  "javascript",
  "c",
  "java",
  "react",
  "astro",
  "amazons3",
  "html5",
  "css3",
  "python",
  "express",
  "mongodb",
  "amazonec2",
  "amazonwebservices",
  "nodedotjs",
  "firebase",
  "netlify",
  "stripe",
  "cypress",
  "cypress",
  "unity",
  "git",
  "jira",
  "github",
  "pandas",
  "visualstudiocode",
  "r",
  "mysql",
  "figma",
  "flask",
];
